# Generated by Django 5.1.6 on 2026-03-04 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_account_opening_balance_cents_transfer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('store', models.CharField(blank=True, max_length=255, null=True)),
                ('tax_cents', models.BigIntegerField(default=0)),
                ('fees_cents', models.BigIntegerField(default=0)),
                ('total_cents', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GroceryTripItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_snapshot', models.CharField(max_length=255)),
                ('qty', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_price_cents', models.BigIntegerField(blank=True, null=True)),
                ('line_total_cents', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('default_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('signed_amount_cents', 0), _negated=True), name='transaction_signed_amount_non_zero'),
        ),
        migrations.AddField(
            model_name='grocerytrip',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='grocery_trip', to='finance.transaction'),
        ),
        migrations.AddField(
            model_name='grocerytripitem',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.grocerytrip'),
        ),
        migrations.AddField(
            model_name='grocerytripitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_items', to='finance.product'),
        ),
        migrations.AddConstraint(
            model_name='grocerytrip',
            constraint=models.CheckConstraint(condition=models.Q(('tax_cents__gte', 0)), name='grocery_trip_tax_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='grocerytrip',
            constraint=models.CheckConstraint(condition=models.Q(('fees_cents__gte', 0)), name='grocery_trip_fees_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='grocerytrip',
            constraint=models.CheckConstraint(condition=models.Q(('total_cents__gte', 0)), name='grocery_trip_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='grocerytripitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_total_cents__gte', 0)), name='grocery_trip_item_line_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='grocerytripitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price_cents__isnull', True), ('unit_price_cents__gte', 0), _connector='OR'), name='grocery_trip_item_unit_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='grocerytripitem',
            constraint=models.CheckConstraint(condition=models.Q(('qty__isnull', True), ('qty__gt', 0), _connector='OR'), name='grocery_trip_item_qty_positive'),
        ),
    ]
