# Generated by Django 5.1.6 on 2026-03-05 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_grocerytrip_grocerytripitem_product_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroceryTrip',
            new_name='Receipt',
        ),
        migrations.RenameModel(
            old_name='GroceryTripItem',
            new_name='ReceiptItem',
        ),
        migrations.RenameField(
            model_name='receiptitem',
            old_name='trip',
            new_name='receipt',
        ),
        migrations.AlterField(
            model_name='receipt',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='finance.transaction'),
        ),
        migrations.AlterField(
            model_name='receiptitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_items', to='finance.product'),
        ),
        migrations.AlterField(
            model_name='receiptitem',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.receipt'),
        ),
        migrations.RemoveConstraint(
            model_name='receipt',
            name='grocery_trip_tax_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='receipt',
            name='grocery_trip_fees_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='receipt',
            name='grocery_trip_total_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='receiptitem',
            name='grocery_trip_item_line_total_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='receiptitem',
            name='grocery_trip_item_unit_price_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='receiptitem',
            name='grocery_trip_item_qty_positive',
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.CheckConstraint(condition=models.Q(('tax_cents__gte', 0)), name='receipt_tax_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.CheckConstraint(condition=models.Q(('fees_cents__gte', 0)), name='receipt_fees_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.CheckConstraint(condition=models.Q(('total_cents__gte', 0)), name='receipt_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='receiptitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_total_cents__gte', 0)), name='receipt_item_line_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='receiptitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price_cents__isnull', True), ('unit_price_cents__gte', 0), _connector='OR'), name='receipt_item_unit_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='receiptitem',
            constraint=models.CheckConstraint(condition=models.Q(('qty__isnull', True), ('qty__gt', 0), _connector='OR'), name='receipt_item_qty_positive'),
        ),
    ]
